name: Release

on:
  release:
    types: [published, created, edited]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Setup nuget
      uses: nuget/setup-nuget@v1
    - name: Update nuget source
      run: |
        nuget sources update -Name 'github' `
                             -Source https://nuget.pkg.github.com/aprismatic/index.json `
                             -UserName ${{ secrets.GithubUsername }} `
                             -Password ${{ secrets.GithubToken }} `
                             -ConfigFile ./nuget.config
    - name: Restore packages
      run: nuget restore
    - name: Build with msbuild
      run: msbuild -p:Configuration=Release -p:Version=${{ github.event.release.tag_name }}
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-artifacts
        path: .

  test:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v1
      with:
        name: build-artifacts
        path: .
    - name: Run tests
      run: dotnet test --configuration Release --no-build

  publish:
    needs: test
    runs-on: windows-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v1
      with:
        name: build-artifacts
        path: .
    - name: Setup nuget
      uses: nuget/setup-nuget@v1
    - name: Update nuget source
      run: |
        nuget sources update -Name 'github' `
                             -Source https://nuget.pkg.github.com/aprismatic/index.json `
                             -UserName ${{ secrets.GithubUsername }} `
                             -Password ${{ secrets.GithubToken }} `
                             -ConfigFile ./nuget.config
    - name: Pack nuget packages
      run: dotnet pack --configuration Release --no-build -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:PackageVersion=${{ github.event.release.tag_name }}
    - name: Publish nuget packages
      run: dotnet nuget push **/*.nupkg --source "github"